use octocrab::{Octocrab, models::AppId, models::InstallationId};
use jsonwebtoken::EncodingKey;
use std::env;
use std::fs;
use dotenvy::dotenv;

pub struct App {
    pub client: Octocrab,
}

impl App {
    pub fn new() -> Result<Self, Box<dyn std::error::Error>> {
        dotenv().ok(); // load variables from .env into system env
        // will change to load from Secret Manager probs

        let app_secret = env::var("GITHUB_APP_ID").expect("GITHUB_APP_ID must be set!");
        // let webhook_secret = env::var("WEBHOOK_SECRET").expect("WEBHOOK_SECRET must be set!");
        let key_secret = env::var("PRIVATE_KEY").expect("PRIVATE_KEY must be set!");

        // setting up the app settings
        let app_id = AppId(app_secret.parse()?);
        let key_contents = fs::read_to_string(key_secret)?;
        let encoding_key = EncodingKey::from_rsa_pem(key_contents.as_bytes())?;

        // installing app
        let app_client = Octocrab::builder()
            .app(app_id, encoding_key)
            .build()?;

        Ok(Self {
            client: app_client,
        })

    }
    /* 
    pub fn add_issue(self, id: InstallationId) -> Result<(), Box<dyn std::error::Error>> {
        // get the repo from the installation id
        let repo_client = self.client.installation(id)?;
        let issue = repo_client.issues("owner", "repo")
            .create("KIND + LINE")
            .labels() // the vector labels
            .assignees() // you
            .send()
            .await>;


        let issue = octocrab.issues("owner", "repo").create("My first issue")
        // Optional Parameters
        .body("This is an autogenerated issue..")
        .milestone(1001)
        .labels(vec![String::from("help-wanted")])
        .assignees(vec![String::from("ferris")])
        // Send the request
        .send()
        .await?;

        // then issue number is 
        issue.number
    } */

}
